env:
  ANSIBLE_FORCE_COLOR: "1"
  CIRRUS_WORKING_DIR: /home/ubuntu
  CIRRUS_SHELL: sudo -Hu ubuntu bash

test_task:
  # safer timeout value
  timeout_in: 120m

  compute_engine_instance:
    image_project: ubuntu-os-cloud
    image: family/ubuntu-2204-lts

  install_ansible_script: |-
    sudo add-apt-repository -y ppa:ansible/ansible
    sudo apt install -y ansible

  install_ansible_roles_script: |-
    ansible-galaxy install -r requirements.yaml

  print_ansible_debug_information_script: |-
    ansible --version
    ansible-galaxy collection list
    ansible-config dump --only-changed

  test_playbook_syntax_script: |-
    ansible-playbook desktop.yaml --syntax-check

  test_playbook_script: |-
    ansible-playbook --skip-tags no-ci -v desktop.yaml

  # Idempotence check taken from:
  # https://github.com/geerlingguy/mac-dev-playbook/blob/c42f8822dd7f82ad6ba3c95ca3a136279926c990/.github/workflows/ci.yml#L71-L77
  idempotence_check_script: |-
    idempotence=$(mktemp)
    ansible-playbook --skip-tags no-ci desktop.yaml -v | tee -a ${idempotence}
    sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" ${idempotence} \
      | grep -E '^localhost +:' | tail -n 1 | grep -q 'changed=0.*failed=0' \
        && (echo 'Idempotence test: pass' && exit 0) \
        || (echo 'Idempotence test: fail' && exit 1)
