repos:
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.5.0
    hooks:
      - id: ansible-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: |-
          (?x)^
          templates/Cinnamenu@json\.json\.j2
          $
      - id: mixed-line-ending
        args:
          - "--fix=lf"

      # Trailing whitespace is evil
      - id: trailing-whitespace

      # Ensure that links to code on GitHub use the permalinks
      - id: check-vcs-permalinks

      # Checks for git-related issues
      - id: check-case-conflict
      - id: check-merge-conflict
