---
- name: Provision desktop.
  hosts: localhost
  connection: local

  vars:
    ubuntu_codename: >-
      {{
        lookup('file', '/etc/os-release')
        | regex_search('^UBUNTU_CODENAME=(.*)$', '\1', multiline=True)
        | first
      }}

  tasks:
    - name: Gather the package facts.
      ansible.builtin.package_facts:
        manager: auto

    - name: Ensure basic utilities are present.
      become: true
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - build-essential
          - curl
          - git
        state: present

    # snap is required to install chezmoi
    - import_tasks: tasks/install_snap.yaml
    - import_tasks: tasks/install_dotfiles.yaml

    - import_tasks: tasks/add_repository_keys.yaml

    - import_tasks: tasks/install_appimaged.yaml
    - import_tasks: tasks/install_language_runtimes.yaml

    - import_tasks: tasks/install_shell_and_terminal.yaml
    - import_tasks: tasks/install_devtools_cli.yaml
    - import_tasks: tasks/install_devtools_gui.yaml
    - import_tasks: tasks/install_fonts.yaml
    - import_tasks: tasks/install_desktop_environment_extensions.yaml
    - import_tasks: tasks/install_general.yaml

    - import_tasks: tasks/configure_desktop_environment.yaml
    - import_tasks: tasks/configure_services.yaml
    - import_tasks: tasks/prepare_dev_environment.yaml

    # See README for things to do post-provisioning.
