---
- name: Add the AnyDesk repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    key_name: anydesk
    key_id: null
    dearmor: true

- name: Add the Enpass repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://apt.enpass.io/keys/enpass-linux.key
    key_name: enpass
    key_id: B6DA722E2E65721AF54B93966F7565879798C2FC
    dearmor: true

- name: Add the GitHub CLI repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    key_name: githubcli
    key_id: null
    dearmor: false

- name: Add the Google repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    key_name: google
    key_id: null
    dearmor: true

- name: Add the Hashicorp repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://apt.releases.hashicorp.com/gpg
    key_name: hashicorp
    key_id: E8A032E094D8EB4EA189D270DA418C88A3219F7B
    dearmor: true

- name: Add the Heroku CLI repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://cli-assets.heroku.com/apt/release.key
    key_name: herokucli
    key_id: null
    dearmor: true

- name: Add the Microsoft repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://packages.microsoft.com/keys/microsoft.asc
    key_name: microsoft
    key_id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    dearmor: true

- name: Add the MKVToolNix repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg
    key_name: mkvtoolnix
    key_id: D9199745B0545F2E8197062B0F92290A445B9007
    dearmor: false

- name: Add the NodeSource package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    key_name: nodesource
    key_id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    dearmor: true

- name: Add the OnlyOffice repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCB2DE8E5
    key_name: onlyoffice
    key_id: E09CA29F6E178040EF22B4098320CA65CB2DE8E5
    dearmor: true

- name: Add the Spotify repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    key_name: spotify
    key_id: F9A211976ED662F00E59361E5E3C45D7B312C643
    dearmor: true

- name: Add the Sublime HQ repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    key_name: sublimehq
    key_id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
    dearmor: true

- name: Add the Eugeny Tabby repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://packagecloud.io/eugeny/tabby/gpgkey
    key_name: eugeny_tabby
    key_id: null
    dearmor: true

- name: Add the Volian Scar repository package signing key.
  ansible.builtin.import_role:
    name: jack1142.apt_signing_key
  vars:
    url: https://deb.volian.org/volian/scar.key
    key_name: volian-scar-unstable
    key_id: A1F2145635241E0E974647AEA87015F3DA22D980
    dearmor: false
