---
- name: Configure GRUB to only include the current system and skip menu.
  become: true
  block:
    - name: Create configuration file.
      register: grub_my_custom_config
      ansible.builtin.copy:
        dest: /etc/default/grub.d/90_my_custom_config.cfg
        content: |
          GRUB_TIMEOUT=0
          GRUB_TIMEOUT_STYLE=hidden
          GRUB_DISABLE_OS_PROBER=true

    - name: Generate a grub config file (update-grub).
      ansible.builtin.command:
        cmd: update-grub
      when: grub_my_custom_config is changed

- name: Disable hibernation.
  become: true
  block:
    - name: Create /etc/systemd/sleep.conf.d directory
      ansible.builtin.file:
        path: /etc/systemd/sleep.conf.d
        state: directory

    - name: Create nohibernation.conf file.
      ansible.builtin.copy:
        dest: /etc/systemd/sleep.conf.d/nohibernation.conf
        content: |
          [Sleep]
          AllowHibernation=no
          AllowSuspendThenHibernate=no
          AllowHybridSleep=no

- name: Set Super key as special key to move and resize Windows ("Alt snap").
  community.general.dconf:
    key: /org/cinnamon/desktop/wm/preferences/mouse-button-modifier
    value: "'<Super>'"
    state: present

- name: Make mouse scroll on title bar shade and unshade the window.
  community.general.dconf:
    key: /org/cinnamon/desktop/wm/preferences/action-scroll-titlebar
    value: "'shade'"
    state: present

- name: Maximize, instead of tile, when dragging a window to the top edge.
  community.general.dconf:
    key: /org/cinnamon/muffin/tile-maximize
    value: "true"
    state: present

- name: Ensure Opacify Windows Cinnamon extension is installed and enabled.
  block:
    - name: Download and install Opacify Windows.
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://cinnamon-spices.linuxmint.com/files/extensions/opacify@anish.org.zip?time={{ ansible_date_time.epoch }}"
        dest: "{{ ansible_user_dir }}/.local/share/cinnamon/extensions"
        creates: "{{ ansible_user_dir }}/.local/share/cinnamon/extensions/opacify@anish.org"

    - name: Enable Opacify Windows.
      community.general.dconf:
        key: /org/cinnamon/enabled-extensions
        value: "['opacify@anish.org']"
        state: present

- name: Show date and seconds in system clock.
  community.general.dconf:
    key: "{{ item }}"
    value: "true"
    state: present
  loop:
    - /org/cinnamon/desktop/interface/clock-show-date
    - /org/cinnamon/desktop/interface/clock-show-seconds

- name: Set Monday as first day of week in the calendar.
  community.general.dconf:
    key: /org/cinnamon/desktop/interface/first-day-of-week
    value: "1"
    state: present

- name: Set power button to suspend.
  community.general.dconf:
    key: /org/cinnamon/settings-daemon/plugins/power/button-power
    value: "'suspend'"
    state: present

- name: Set custom system clock format.
  ansible.builtin.template:
    src: templates/calendar@cinnamon.org.json.j2
    dest: "{{ item }}"
  with_fileglob:
    - "{{ ansible_user_dir }}/.cinnamon/configs/calendar@cinnamon.org/*.json"

- name: Set application shortcuts on taskbar.
  ansible.builtin.template:
    src: templates/grouped-window-list@cinnamon.org.json.j2
    dest: "{{ item }}"
  with_fileglob:
    - "{{ ansible_user_dir }}/.cinnamon/configs/grouped-window-list@cinnamon.org/*.json"
  vars:
    pinned_apps:
      - nemo.desktop
      - google-chrome.desktop
      - org.gnome.Calculator.desktop

- name: Set custom opacity in Opacify Windows extension.
  ansible.builtin.template:
    src: templates/opacify@anish.org.json.j2
    dest: "{{ item }}"
  with_fileglob:
    - "{{ ansible_user_dir }}/.cinnamon/configs/opacify@anish.org/opacify@anish.org.json"

- name: Disable Show desktop applet.
  tags:
    - no-ci  # can't read a value in CI as it is not already set
  block:
    - name: Get current enabled applets.
      community.general.dconf:
        key: /org/cinnamon/enabled-applets
        state: read
      register: enabled_applets

    - name: Set enabled applets without Show desktop applet.
      community.general.dconf:
        key: /org/cinnamon/enabled-applets
        value: |-
          {{
            enabled_applets.value
            | from_yaml
            | reject('match', '.*show-desktop@cinnamon\.org.*')
            | list
            | string
          }}
        state: present

- name: Use Cinnamenu applet instead of the default menu applet.
  tags:
    - no-ci  # can't read a value in CI as it is not already set
  block:
    - name: Download and install Cinnamenu.
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://cinnamon-spices.linuxmint.com/files/applets/Cinnamenu@json.zip?time={{ ansible_date_time.epoch }}"
        dest: "{{ ansible_user_dir }}/.local/share/cinnamon/applets"
        creates: "{{ ansible_user_dir }}/.local/share/cinnamon/applets/Cinnamenu@json"

    - name: Create ~/.cinnamon/configs/Cinnamenu@json directory.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.cinnamon/configs/Cinnamenu@json"
        state: directory

    - name: Configure Cinnamenu.
      ansible.builtin.template:
        src: templates/Cinnamenu@json.json.j2
        dest: "{{ item }}"
      vars:
        item: "{{ ansible_user_dir }}/.cinnamon/configs/Cinnamenu@json/0.json"

    - name: Get current enabled applets.
      community.general.dconf:
        key: /org/cinnamon/enabled-applets
        state: read
      register: enabled_applets

    - name: Replace menu@cinnamon.org applet with Cinnamenu@json.
      community.general.dconf:
        key: /org/cinnamon/enabled-applets
        value: |-
          {{
            enabled_applets.value
            | from_yaml
            | map('regex_replace', '^(.*):menu@cinnamon\.org:0$', '\1:Cinnamenu@json:0')
            | list
            | string
          }}
        state: present

    - name: Remove configuration file for menu@cinnamon.org.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.cinnamon/configs/menu@cinnamon.org/0.json"
        state: absent

- name: Set default browser to Google Chrome.
  community.general.alternatives:
    name: "{{ item }}"
    path: /usr/bin/google-chrome-stable
  loop:
    - x-www-browser
    - gnome-www-browser

- name: Set the list of favourite apps.
  community.general.dconf:
    key: /org/cinnamon/favorite-apps
    value: "{{ favourite_apps | string }}"
  vars:
    favourite_apps:
      - kitty.desktop
      - sublime_text.desktop
      - sublime_merge.desktop
      - google-chrome.desktop
      - firefox.desktop
      - enpass.desktop
      - xed.desktop
      - discord.desktop
      - microsoft-edge.desktop
      - opera_opera.desktop
      - tv.plex.PlexMediaPlayer.desktop:flatpak
      - spotify_spotify.desktop
      - steam.desktop
      - gimp.desktop
      - org.inkscape.Inkscape.desktop
      - onlyoffice-desktopeditors.desktop
      - insomnia_insomnia.desktop
      - virtualbox.desktop
      - virt-manager.desktop
      - com.obsproject.Studio.desktop
      - org.gnome.Calculator.desktop

- name: Setup keyboard shortcuts.
  block:
    - name: Disable default screenshot shortcuts.
      community.general.dconf:
        key: "{{ item }}"
        value: '@as []'
        state: present
      loop:
        - /org/cinnamon/desktop/keybindings/media-keys/area-screenshot
        - /org/cinnamon/desktop/keybindings/media-keys/window-screenshot-clip
        - /org/cinnamon/desktop/keybindings/media-keys/window-screenshot
        - /org/cinnamon/desktop/keybindings/media-keys/screenshot-clip
        - /org/cinnamon/desktop/keybindings/media-keys/screenshot
        - /org/cinnamon/desktop/keybindings/media-keys/area-screenshot-clip
        - /org/cinnamon/desktop/keybindings/wm/toggle-recording

    - name: Configure custom keybindings.
      community.general.dconf:
        key: /org/cinnamon/desktop/keybindings/custom-keybindings/custom{{ item.index }}/{{ item.key }}
        value: "{{ item.value }}"
      loop:
        - {index: 0, key: name, value: "'Take a screenshot of a region'"}
        - {index: 0, key: binding, value: "['Print']"}
        - {index: 0, key: command, value: "'shutter --select'"}

        - {index: 1, key: name, value: "'Take a screenshot of the entire screen'"}
        - {index: 1, key: binding, value: "['<Primary>Print']"}
        - {index: 1, key: command, value: "'shutter --full'"}

        - {index: 2, key: name, value: "'Disable Insert Key'"}
        - {index: 2, key: binding, value: "['Insert']"}
        - {index: 2, key: command, value: "'/bin/true'"}

    - name: Save custom keybindings.
      community.general.dconf:
        key: /org/cinnamon/desktop/keybindings/custom-list
        value: "['__dummy__', 'custom0', 'custom1', 'custom2']"
