---
- name: Configure GRUB to only include the current system and skip menu.
  become: true
  block:
    - name: Create configuration file.
      register: grub_my_custom_config
      ansible.builtin.copy:
        dest: /etc/default/grub.d/90_my_custom_config.cfg
        content: |
          GRUB_TIMEOUT=0
          GRUB_TIMEOUT_STYLE=hidden
          GRUB_DISABLE_OS_PROBER=true

    - name: Generate a grub config file (update-grub).
      ansible.builtin.command:
        cmd: update-grub
      when: grub_my_custom_config is changed

- name: Enable scroll on middle mouse button hold.
  become: true
  block:
    - name: Create /etc/X11/xorg.conf.d directory.
      ansible.builtin.file:
        path: /etc/X11/xorg.conf.d
        state: directory

    - name: Create configuration file.
      ansible.builtin.copy:
        dest: /etc/X11/xorg.conf.d/90-enable-button-scroll-method.conf
        content: |
          Section "InputClass"
            Identifier   "My Current Mouse"
            MatchProduct "Glorious Model D"
            Driver       "libinput"
            Option       "ScrollMethod"    "button"
          EndSection

- name: Disable hibernation.
  become: true
  block:
    - name: Create /etc/systemd/sleep.conf.d directory
      ansible.builtin.file:
        path: /etc/systemd/sleep.conf.d
        state: directory

    - name: Create nohibernation.conf file.
      ansible.builtin.copy:
        dest: /etc/systemd/sleep.conf.d/nohibernation.conf
        content: |
          [Sleep]
          AllowHibernation=no
          AllowSuspendThenHibernate=no
          AllowHybridSleep=no

- name: Set default browser to Google Chrome.
  community.general.alternatives:
    name: "{{ item }}"
    path: /usr/bin/google-chrome-stable
  loop:
    - x-www-browser
    - gnome-www-browser
