---
- name: Configure GRUB to only include the current system and skip menu.
  become: true
  block:
    - name: Create configuration file.
      register: grub_my_custom_config
      ansible.builtin.copy:
        dest: /etc/default/grub.d/90_my_custom_config.cfg
        content: |
          GRUB_TIMEOUT=0
          GRUB_TIMEOUT_STYLE=hidden
          GRUB_DISABLE_OS_PROBER=true
        mode: '0644'

    - name: Generate a grub config file (update-grub).
      ansible.builtin.command:
        cmd: update-grub
      when: grub_my_custom_config is changed

- name: Disable hibernation.
  become: true
  block:
    - name: Create /etc/systemd/sleep.conf.d directory
      ansible.builtin.file:
        path: /etc/systemd/sleep.conf.d
        state: directory
        mode: '0755'

    - name: Create nohibernation.conf file.
      ansible.builtin.copy:
        dest: /etc/systemd/sleep.conf.d/nohibernation.conf
        content: |
          [Sleep]
          AllowHibernation=no
          AllowSuspendThenHibernate=no
          AllowHybridSleep=no
        mode: '0644'

- name: Set default browser to Google Chrome.
  community.general.alternatives:
    name: "{{ item }}"
    path: /usr/bin/google-chrome-stable
  loop:
    - x-www-browser
    - gnome-www-browser

- name: Add reboot-windows script and allow running it without password.
  block:
    - name: Create /usr/local/sbin/reboot-windows.
      become: true
      ansible.builtin.copy:
        dest: /usr/local/sbin/reboot-windows
        content: |
          #!/bin/bash -e

          output=$(efibootmgr)
          boot_order=$(echo $output | sed -nr 's/BootOrder: (.+)/\1/p')
          declare -A windows_entries
          while IFS= read -r line; do
              windows_entries[$line]=""
          done < <(echo "$output" | sed -nr 's/Boot([0-9A-F]{4})\* Windows Boot Manager/\1/p')

          windows_bootnum=""
          for bootnum in ${boot_order//,/ }; do
              if [[ -v 'windows_entries[$bootnum]' ]]; then
                  windows_bootnum="$bootnum"
                  break
              fi
          done

          if [[ -z "$windows_bootnum" ]]; then
              echo "Couldn't find Windows Boot Manager entry!"
              exit 1
          fi

          efibootmgr -n "$windows_bootnum"
          reboot
        mode: '0755'
        owner: root
        group: root

    - name: Allow running reboot-windows without password in sudoers.d.
      become: true
      ansible.builtin.copy:
        dest: /etc/sudoers.d/00-allow-reboot-windows
        content: |
          ubuntu ALL = (ALL) NOPASSWD: /usr/local/sbin/reboot-windows
        mode: '0440'
        owner: root
        group: root

    - name: Create Reboot to Windows shortcut on desktop.
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/Desktop/RebootToWindows.desktop"
        content: |
          [Desktop Entry]
          Name=Reboot to Windows
          Exec=kdialog --title 'Reboot to Windows' --yesno 'Are you sure that you want to reboot to Windows?' && sudo reboot-windows
          Icon=system-run
          Type=Application
          StartupNotify=true
        mode: '0755'

- name: Use Cloudflare DNS over TLS.
  become: true
  block:
    - name: Create /etc/systemd/resolved.conf.d directory.
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: '0755'

    - name: Create configuration file.
      ansible.builtin.copy:
        dest: /etc/systemd/resolved.conf.d/use_cloudflare_dns_over_tls.conf
        content: |
          [Resolve]
          DNS=1.1.1.1 1.0.0.1 8.8.8.8
          FallbackDNS=1.1.1.1 1.0.0.1 8.8.8.8
          DNSSEC=no
          DNSOverTLS=yes
        mode: '0644'

- name: Install XMousePasteBlock.
  block:
    - name: Add XMousePasteBlock repository.
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:jackenmen/xmousepasteblock
        codename: "{{ ubuntu_codename }}"
        state: present

    - name: Install XMousePasteBlock.
      become: true
      ansible.builtin.apt:
        name: xmousepasteblock
        state: present

    - name: Enable the xmousepasteblock user service.
      ansible.builtin.systemd:
        name: xmousepasteblock
        state: started
        enabled: true
        scope: user
      tags:
        - no-ci  # this task doesn't work in CI due to no user systemd
