---
- name: Install Audacity.
  become: true
  ansible.builtin.apt:
    name: audacity
    state: present

- name: Install Discord.
  become: true
  when: "'discord' not in ansible_facts.packages"
  ansible.builtin.apt:
    deb: https://discord.com/api/download?platform=linux&format=deb
    state: present

- name: Install drawio.
  become: true
  community.general.snap:
    name: drawio
    state: present

- name: Install ffmpeg.
  become: true
  ansible.builtin.apt:
    name: ffmpeg
    state: present

- name: Install Enpass.
  become: true
  block:
    - name: Add the Enpass repository.
      ansible.builtin.apt_repository:
        repo: >-
          deb [signed-by=/usr/share/keyrings/enpass-archive-keyring.gpg]
          https://apt.enpass.io/ stable main
        state: present

    - name: Install Enpass.
      ansible.builtin.apt:
        name: enpass
        state: present

- name: Install GIMP.
  become: true
  ansible.builtin.apt:
    name: gimp
    state: present

- name: Install Google Chrome.
  become: true
  block:
    - name: Prevent Google Chrome package from adding its own GPG key.
      ansible.builtin.copy:
        dest: /etc/default/google-chrome
        content: |
          echo -n '/etc/default/google-chrome has prevented Google Chrome'
          echo    ' package from adding gpg key to /etc/apt/trusted.gpg.d/'
          exit 0

    - name: Add the Google Chrome repository.
      ansible.builtin.apt_repository:
        # This needs to be exactly 'google-chrome' to prevent Google Chrome
        # from adding this repository for the second time.
        filename: google-chrome
        repo: >-
          deb [arch=amd64 signed-by=/usr/share/keyrings/google-archive-keyring.gpg]
          https://dl.google.com/linux/chrome/deb/ stable main
        state: present

    - name: Install Google Chrome.
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present

- name: Install Google Chrome Remote Desktop.
  become: true
  block:
    - name: Prevent Google Chrome Remote Desktop package from adding its own GPG key.
      ansible.builtin.copy:
        dest: /etc/default/chrome-remote-desktop
        content: |
          echo -n '/etc/default/chrome-remote-desktop has prevented'
          echo -n ' Google Chrome Remote Desktop package'
          echo    ' from adding gpg key to /etc/apt/trusted.gpg.d/'
          exit 0

    - name: Add the Google Chrome Remote Desktop repository.
      ansible.builtin.apt_repository:
        # This needs to be exactly 'chrome-remote-desktop' to prevent
        # Google Chrome Remote Desktop from adding this repository for the second time.
        filename: chrome-remote-desktop
        repo: >-
          deb [arch=amd64 signed-by=/usr/share/keyrings/google-archive-keyring.gpg]
          http://dl.google.com/linux/chrome-remote-desktop/deb/ stable main
        state: present

    - name: Install Google Chrome Remote Desktop.
      ansible.builtin.apt:
        name: chrome-remote-desktop
        state: present

- name: Install Inkscape.
  become: true
  block:
    - name: Add Inkscape stable repository
      ansible.builtin.apt_repository:
        repo: ppa:inkscape.dev/stable
        codename: "{{ ubuntu_codename }}"
        state: present

    - name: Install Inkscape.
      ansible.builtin.apt:
        name: inkscape
        state: present

- name: Install JDownloader 2.
  become: true
  community.general.snap:
    name: jdownloader2
    state: present

- name: Install Kdenlive.
  become: true
  block:
    - name: Add the Kdenlive repository.
      ansible.builtin.apt_repository:
        repo: ppa:kdenlive/kdenlive-stable
        codename: "{{ ubuntu_codename }}"
        state: present

    - name: Install Kdenlive.
      ansible.builtin.apt:
        name: kdenlive
        state: present

- name: Install ksnip.
  block:
    - name: Make Screenshots directory.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/Pictures/Screenshots"
        state: directory

    - name: Install ksnip.
      become: true
      ansible.builtin.apt:
        name: ksnip
        state: present

- name: Install Microsoft Edge.
  become: true
  block:
    - name: Prevent Microsoft Edge package from adding its own GPG key.
      ansible.builtin.copy:
        dest: /etc/default/microsoft-edge
        content: |
          echo -n '/etc/default/microsoft-edge has prevented Microsoft Edge'
          echo    ' package from adding gpg key to /etc/apt/trusted.gpg.d/'
          exit 0

    - name: Add the Microsoft Edge repository.
      ansible.builtin.apt_repository:
        # This needs to be exactly 'microsoft-edge' to prevent Microsoft Edge
        # from adding this repository for the second time.
        filename: microsoft-edge
        repo: >-
          deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg]
          https://packages.microsoft.com/repos/edge/ stable main
        state: present

    - name: Install Microsoft Edge.
      ansible.builtin.apt:
        name: microsoft-edge-stable
        state: present

- name: Install MKVToolNix.
  become: true
  block:
    - name: Add the MKVToolNix repository.
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/usr/share/keyrings/mkvtoolnix-archive-keyring.gpg]
          https://mkvtoolnix.download/ubuntu/ {{ ubuntu_codename }} main
        state: present

    - name: Install MKVToolNix.
      ansible.builtin.apt:
        name:
          - mkvtoolnix
          - mkvtoolnix-gui
        state: present

- name: Install OBS Studio.
  become: true
  block:
    - name: Add OBS Studio repository.
      ansible.builtin.apt_repository:
        repo: ppa:obsproject/obs-studio
        codename: "{{ ubuntu_codename }}"
        state: present

    - name: Install OBS Studio.
      ansible.builtin.apt:
        name: obs-studio
        state: present

- name: Install Opera.
  become: true
  community.general.snap:
    name: opera
    state: present

- name: Install Microsoft Teams.
  block:
    - name: Add the Microsoft Teams repository.
      become: true
      ansible.builtin.apt_repository:
        # This needs to be exactly 'teams' to prevent Microsoft Teams
        # from adding this repository for the second time.
        filename: teams
        repo: >-
          deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg]
          https://packages.microsoft.com/repos/ms-teams stable main
        state: present

    - name: Install Microsoft Teams.
      become: true
      ansible.builtin.apt:
        name: teams
        state: present

    - name: Create ~/.config/Microsoft/Microsoft Teams directory.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/Microsoft/Microsoft Teams"
        state: directory

    - name: Disable auto-start of MS Teams.
      ansible.builtin.template:
        src: templates/ms-teams-desktop-config.json.j2
        dest: "{{ item }}"
      vars:
        item: "{{ ansible_user_dir }}/.config/Microsoft/Microsoft Teams/desktop-config.json"

- name: Install OnlyOffice.
  become: true
  block:
    - name: Add the OnlyOffice repository.
      ansible.builtin.apt_repository:
        repo: >-
          deb [signed-by=/usr/share/keyrings/onlyoffice-archive-keyring.gpg]
          https://download.onlyoffice.com/repo/debian squeeze main
        state: present

    - name: Install OnlyOffice.
      ansible.builtin.apt:
        name: onlyoffice-desktopeditors
        state: present

- name: Install PlayOnLinux and winbind (Office's requirement).
  become: true
  ansible.builtin.apt:
    name:
      - playonlinux
      - winbind

- name: Install Plex Media Player.
  become: true
  block:
    - name: Add Plex Media Player flatpak repository.
      community.general.flatpak_remote:
        name: plex-media-player
        flatpakrepo_url: https://flatpak.knapsu.eu/plex-media-player.flatpakrepo
        state: present

    - name: Install Plex Media Player.
      community.general.flatpak:
        remote: plex-media-player
        name: tv.plex.PlexMediaPlayer
        state: present

- name: Install PulseAudio Volume Control (pavucontrol).
  become: true
  ansible.builtin.apt:
    name: pavucontrol
    state: present

- name: Install Spotify.
  become: true
  community.general.snap:
    name: spotify
    state: present

- name: Install Steam.
  become: true
  ansible.builtin.apt:
    name: steam
    state: present

- name: Install Teamviewer.
  become: true
  ansible.builtin.apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    state: present

- name: Install TeX Studio.
  become: true
  ansible.builtin.apt:
    name:
      - texlive
      - texstudio
    state: present

- name: Install Unified Remote Server (urserver).
  become: true
  when: "'urserver' not in ansible_facts.packages"
  ansible.builtin.apt:
    deb: https://www.unifiedremote.com/download/linux-x64-deb
    state: present

- name: Install VLC.
  become: true
  ansible.builtin.apt:
    name: vlc
    state: present

- name: Install qBittorrent.
  become: true
  ansible.builtin.apt:
    name: qbittorrent
    state: present

- name: Install QDirStat.
  become: true
  ansible.builtin.apt:
    name: qdirstat
    state: present
