---
- name: Install extensions for Nemo (file manager).
  become: true
  ansible.builtin.apt:
    name:
      - nemo-audio-tab
      - nemo-compare
      - nemo-gtkhash
      - nemo-image-converter
      - nemo-media-columns
    state: present
