---
- name: Install ARandR.
  become: true
  ansible.builtin.apt:
    name: arandr
    state: present

- name: Install autorandr.
  become: true
  ansible.builtin.apt:
    name: autorandr
    state: present

- name: Install Checksum Blister for Dolphin.
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/KVAnton-WEB/Checksum-Blister/master/checksum_blister
    dest: /usr/local/bin/checksum_blister
    mode: +x
