---
- name: Install snapd.
  become: true
  block:
    - name: Remove nosnap.pref.
      ansible.builtin.file:
        path: /etc/apt/preferences.d/nosnap.pref
        state: absent

    - name: Install snapd.
      ansible.builtin.apt:
        name: snapd
        state: present
