---
- name: Create ~/.local/bin folder.
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: Install zsh.
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install sheldon.
  community.general.cargo:
    name: sheldon
    state: present

- name: Install fzf.
  become: true
  ansible.builtin.apt:
    name: fzf
    state: present

- name: Install kitty.
  block:
    - name: Install kitty.
      ansible.builtin.command:
        stdin: "{{ lookup('ansible.builtin.url', kitty_installer_url, split_lines=False) }}"
        cmd: sh /dev/stdin launch=n
        creates: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
      vars:
        kitty_installer_url: https://sw.kovidgoyal.net/kitty/installer.sh

    - name: Symlink kitty executable.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/bin/kitty"
        src: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
        state: link

    - name: Create ~/.local/share/applications directory.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/share/applications"
        state: directory

    - name: Create desktop shortcut.
      ansible.builtin.template:
        src: templates/kitty.desktop.j2
        dest: "{{ ansible_user_dir }}/.local/share/applications/kitty.desktop"

- name: Change current user's login shell to zsh.
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

# in case I ever need/want to use Gnome Terminal instead of kitty...
- name: Change font used by Gnome Terminal.
  block:
    - name: Enable custom font.
      community.general.dconf:
        key: "{{ profile_path }}/use-system-font"
        value: "false"
        state: present

    - name: Choose font.
      community.general.dconf:
        key: "{{ profile_path }}/font"
        value: "'SauceCodePro Nerd Font Mono 11'"
        state: present
  vars:
    profile_path: |-
      /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9
