---
- name: Install Nix.
  become: true
  block:
    - name: Install nix-setup-systemd.
      ansible.builtin.apt:
        name: nix-setup-systemd
        state: present

    # this is needed because the alteration of PATHs in environment.d do not work
    - name: Add Nix's binary paths to PATH.
      ansible.builtin.copy:
        dest: /etc/profile.d/add-nix-bin-paths.sh
        # noqa var-spacing
        content: |
          nix_bin_paths="$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin"
          if [ -n "${PATH##*${nix_bin_paths}}" ] && [ -n "${PATH##*${nix_bin_paths}:*}" ]; then
              export PATH="${nix_bin_paths}:$PATH"
          fi
        mode: '0644'
