---
- name: Create ~/.local/bin folder.
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0775'

- name: Install zsh.
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Install sheldon.
  community.general.cargo:
    name: sheldon
    state: present

- name: Install direnv.
  become: true
  ansible.builtin.apt:
    name: direnv
    state: present

- name: Install fzf.
  become: true
  ansible.builtin.apt:
    name: fzf
    state: present

- name: Install kitty.
  block:
    - name: Install kitty.
      ansible.builtin.command:
        stdin: "{{ lookup('ansible.builtin.url', kitty_installer_url, split_lines=False) }}"
        cmd: sh /dev/stdin launch=n
        creates: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
      vars:
        kitty_installer_url: https://sw.kovidgoyal.net/kitty/installer.sh

    - name: Symlink kitty executable.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/bin/kitty"
        src: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
        state: link

    - name: Create ~/.local/share/applications directory.
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/share/applications"
        state: directory
        mode: '0775'

    - name: Create desktop shortcut.
      ansible.builtin.template:
        src: templates/kitty.desktop.j2
        dest: "{{ ansible_user_dir }}/.local/share/applications/kitty.desktop"
        mode: '0664'

    - name: Install kitty-terminfo.
      become: true
      ansible.builtin.apt:
        name: kitty-terminfo
        state: present

- name: Change current user's login shell to zsh.
  become: true
  block:
    - name: Update /etc/zsh/zprofile to source /etc/profile.
      ansible.builtin.blockinfile:
        path: /etc/zsh/zprofile
        block: |
          emulate sh
          source /etc/profile
          emulate zsh
        mode: '0644'

    - name: Update current user's login shell.
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
