---
- name: Install Microsoft's TrueType core fonts for the Web.
  become: true
  block:
    - name: Accept EULA for Microsoft software.
      ansible.builtin.debconf:
        name: ttf-mscorefonts-installer
        question: msttcorefonts/accepted-mscorefonts-eula
        value: "true"
        vtype: select

    - name: Install Microsoft's TrueType core fonts for the Web.
      ansible.builtin.apt:
        name: ttf-mscorefonts-installer
        state: present

- name: Install Microsoft's non-free Office fonts.
  block:
    - name: Create temporary directory for non-free Office fonts
      ansible.builtin.tempfile:
        state: directory
      register: powerpoint_file

    - name: Download PowerPoint Viewer installer.
      ansible.builtin.get_url:
        url: https://archive.org/download/PowerPointViewer_201801/PowerPointViewer.exe
        dest: "{{ powerpoint_file.path }}/PowerPointViewer.exe"
        checksum: sha256:249473568eba7a1e4f95498acba594e0f42e6581add4dead70c1dfb908a09423

    - name: Extract part of the installer with the fonts.
      ansible.builtin.command:
        argv:
          - cabextract
          - "{{ powerpoint_file.path }}/PowerPointViewer.exe"
          - -F
          - ppviewer.cab
        chdir: "{{ powerpoint_file.path }}"

    - name: Extract TTC fonts.
      ansible.builtin.command:
        argv:
          - cabextract
          - "{{ powerpoint_file.path }}/ppviewer.cab"
          - -F
          - "*.TTC"
          - -d
          - "{{ powerpoint_file.path }}/ppviewer/"

    - name: Extract TTF fonts.
      ansible.builtin.command:
        argv:
          - cabextract
          - "{{ powerpoint_file.path }}/ppviewer.cab"
          - -F
          - "*.TTF"
          - -d
          - "{{ powerpoint_file.path }}/ppviewer/"

    - name: Install fonts.
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: "{{ powerpoint_file.path }}/ppviewer"
        dest: /usr/local/share/fonts
  always:
    - name: Remove temporary file.
      ansible.builtin.file:
        path: "{{ powerpoint_file.path }}"
        state: absent
      when: powerpoint_file.path is defined

- name: Install Inconsolata font.
  become: true
  block:
    - name: Create Inconsolata folder.
      ansible.builtin.file:
        path: /usr/local/share/fonts/Inconsolata
        state: directory
        mode: '2755'
      register: inconsolata

    - name: Download and unzip Inconsolata font.
      ansible.builtin.unarchive:
        remote_src: true
        src: https://fonts.google.com/download?family=Inconsolata
        dest: /usr/local/share/fonts/Inconsolata
        extra_opts:
          - -j
        include:
          - static/*
      when: inconsolata.changed
  rescue:
    - name: Remove Inconsolata folder.
      ansible.builtin.file:
        path: /usr/local/share/fonts/Inconsolata
        state: absent

    - name: Re-raise the error.
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result }}"

- name: Install Source Code Pro font.
  become: true
  block:
    - name: Create SourceCodePro folder.
      ansible.builtin.file:
        path: /usr/local/share/fonts/SourceCodePro
        state: directory
        mode: '2755'
      register: sourcecodepro

    - name: Download and unzip Source Code Pro font.
      ansible.builtin.unarchive:
        remote_src: true
        src: https://fonts.google.com/download?family=Source%20Code%20Pro
        dest: /usr/local/share/fonts/SourceCodePro
        extra_opts:
          - -j
        include:
          - static/*
      when: sourcecodepro.changed
  rescue:
    - name: Remove SourceCodePro folder.
      ansible.builtin.file:
        path: /usr/local/share/fonts/SourceCodePro
        state: absent

    - name: Re-raise the error.
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result }}"

- name: Install SauceCodePro Nerd Font Mono font.
  become: true
  block:
    - name: Create SauceCodePro folder.
      ansible.builtin.file:
        path: /usr/local/share/fonts/SauceCodePro
        state: directory
        mode: '2755'
      register: saucecodepro

    - name: Download and unzip SauceCodePro Nerd Font Mono font.
      ansible.builtin.unarchive:
        remote_src: true
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/SourceCodePro.zip
        dest: /usr/local/share/fonts/SauceCodePro
      when: saucecodepro.changed
  rescue:
    - name: Remove SauceCodePro folder.
      ansible.builtin.file:
        path: /usr/local/share/fonts/SauceCodePro
        state: absent

    - name: Re-raise the error.
      ansible.builtin.fail:
        msg: "{{ ansible_failed_result }}"
