---
- name: Install extensions for Nemo (file manager).
  tags:
    - no-ci  # Ubuntu repositories do not have nemo so this doesn't work in CI
  become: true
  ansible.builtin.apt:
    name:
      - nemo-audio-tab
      - nemo-compare
      - nemo-gtkhash
      - nemo-image-converter
      - nemo-media-columns
    state: present
