---
- name: Create work folder in home directory.
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/work"
    state: directory

- name: Ultimately trust my GPG key.
  ansible.builtin.command:
    stdin: "{{ my_key }}"
    cmd: gpg --import-ownertrust
  when: my_key not in lookup('pipe', 'gpg --export-ownertrust 2>/dev/null || :')
  vars:
    my_key: "00354D7E9DD49ED6070F507695A9D6BCDE5C1283:6:"
