name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 4"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      # Checkout repository
      - uses: actions/checkout@v2
      - name: Ensure that the repository's directory is not world-writable.
        run: |
          chmod o-w "$GITHUB_WORKSPACE"

      - name: Make necessary changes to CI environment.
        run: |
          mkdir -p ~/.local/share/applications
          mkdir -p ~/.local/share/cinnamon/applets
          mkdir -p ~/.local/share/cinnamon/extensions
          mkdir -p ~/.cinnamon/configs/calendar@cinnamon.org
          mkdir -p ~/.cinnamon/configs/grouped-window-list@cinnamon.org
          mkdir -p ~/.cinnamon/configs/opacify@anish.org
          sudo apt install dbus dconf-cli flatpak python3-psutil runc
          sudo dpkg --add-architecture i386
          sudo apt-add-repository -y multiverse
          sudo apt-add-repository -y restricted
          sudo apt update

      - name: Install Ansible
        run: |
          sudo add-apt-repository -y ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Install Ansible roles.
        run: /usr/bin/ansible-galaxy install -r requirements.yaml

      - name: Ansible version and configuration debug information.
        run: |
          /usr/bin/ansible --version
          /usr/bin/ansible-galaxy collection list
          /usr/bin/ansible-config dump --only-changed

      - name: Test the playbook's syntax.
        run: /usr/bin/ansible-playbook desktop.yaml --syntax-check

      - name: Test the playbook.
        run: /usr/bin/ansible-playbook --skip-tags no-ci -v desktop.yaml
        env:
          ANSIBLE_FORCE_COLOR: "1"

      # Idempotence check taken from:
      # https://github.com/geerlingguy/mac-dev-playbook/blob/c42f8822dd7f82ad6ba3c95ca3a136279926c990/.github/workflows/ci.yml#L71-L77
      - name: Idempotence check.
        run: |
          idempotence=$(mktemp)
          /usr/bin/ansible-playbook --skip-tags no-ci desktop.yaml -v | tee -a ${idempotence}
          sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" ${idempotence} \
            | grep -E '^localhost +:' | tail -n 1 | grep -q 'changed=0.*failed=0' \
              && (echo 'Idempotence test: pass' && exit 0) \
              || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: "1"
